kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kbp
nodes:
- role: control-plane
  #image: dockerhub.rnd.amadeus.net/devenv-docker-dev-devenv-exp-nce/patched-kind:v1.27.3
- role: worker
  #image: dockerhub.rnd.amadeus.net/devenv-docker-dev-devenv-exp-nce/patched-kind:v1.27.3
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
  - containerPort: 443
    hostPort: 1443
  labels:
    ingress-ready: true
