apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-fileserver
  name: {{ .Release.Name }}-fileserver
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}-fileserver
  sessionAffinity: None
  type: ClusterIP