apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-frontend
  name: {{ .Release.Name }}-frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: {{ .Release.Name }}-frontend
  type: ClusterIP