apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-redis
  name: {{ .Release.Name }}-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: {{ .Release.Name }}-redis
  sessionAffinity: None
  type: ClusterIP
