apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-redis-write
  name: {{ .Release.Name }}-redis-write
spec:
  clusterIP: None
  ports:
  - port: 6379
  selector:
    app: {{ .Release.Name }}-redis
